name: CI

on:
  push:
  pull_request:

jobs:
  validate-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas

      - name: Validate CSVs
        run: python scripts/validate_data.py

      - name: Build docs (ERD)
        run: python scripts/build_docs.py
